# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend('EXTMODS_MISC_USING_K210'):
    src += Glob('k210/*.c')
    CPPPATH += [cwd + '/k210']

group = DefineGroup('extmods', src, depend = ['PRJ_USING_EXTMODS_MISC'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
