#if (defined(EXTMODS_K210_DVP))
QDEF(MP_QSTR_camera, (const byte*)"\xdc\x06" "camera")
QDEF(MP_QSTR_set_pixformat, (const byte*)"\x3a\x0d" "set_pixformat")        
QDEF(MP_QSTR_get_pixformat, (const byte*)"\x2e\x0d" "get_pixformat")        
QDEF(MP_QSTR_set_framesize, (const byte*)"\x20\x0d" "set_framesize")        
QDEF(MP_QSTR_get_framesize, (const byte*)"\x34\x0d" "get_framesize")        


// Image
QDEF(MP_QSTR_image, (const byte*)"\x42\x05" "image")
QDEF(MP_QSTR_Image, (const byte*)"\x62\x05" "Image")
QDEF(MP_QSTR_width, (const byte*)"\x23\x05" "width")
QDEF(MP_QSTR_height, (const byte*)"\xfa\x06" "height")
QDEF(MP_QSTR_resize, (const byte*)"\xb7\x06" "resize")
QDEF(MP_QSTR_crop, (const byte*)"\x0b\x04" "crop")
QDEF(MP_QSTR_PIXFORMAT_JPEG, (const byte*)"\xe0\x0e" "PIXFORMAT_JPEG")
QDEF(MP_QSTR_PIXFORMAT_BINARY, (const byte*)"\x97\x10" "PIXFORMAT_BINARY")
QDEF(MP_QSTR_PIXFORMAT_RGB888_HWC, (const byte*)"\xf4\x14" "PIXFORMAT_RGB888_HWC")
QDEF(MP_QSTR_PIXFORMAT_YUV422, (const byte*)"\xd6\x10" "PIXFORMAT_YUV422")
QDEF(MP_QSTR_PIXFORMAT_RGB888_CHW, (const byte*)"\x54\x14" "PIXFORMAT_RGB888_CHW")
QDEF(MP_QSTR_PIXFORMAT_BAYER, (const byte*)"\x15\x0f" "PIXFORMAT_BAYER")
QDEF(MP_QSTR_PIXFORMAT_INVALID, (const byte*)"\x89\x11" "PIXFORMAT_INVALID")
QDEF(MP_QSTR_PIXFORMAT_GRAYSCALE, (const byte*)"\x4d\x13" "PIXFORMAT_GRAYSCALE")
QDEF(MP_QSTR_PIXFORMAT_RGB565, (const byte*)"\x79\x10" "PIXFORMAT_RGB565")
QDEF(MP_QSTR_mask, (const byte*)"\x91\x04" "mask")
QDEF(MP_QSTR_color_palette, (const byte*)"\x1a\x0d" "color_palette")        
QDEF(MP_QSTR_alpha_palette, (const byte*)"\x93\x0d" "alpha_palette")        
QDEF(MP_QSTR_roi, (const byte*)"\xb1\x03" "roi")
QDEF(MP_QSTR_color, (const byte*)"\xd8\x05" "color")
QDEF(MP_QSTR_thresholds, (const byte*)"\x41\x0a" "thresholds")     
QDEF(MP_QSTR_snapshot, (const byte*)"\x49\x08" "snapshot")
// QDEF(MP_QSTR_sw, (const byte*)"\xe1\x02" "sw")
QDEF(MP_QSTR_RGB565, (const byte*)"\x64\x06" "RGB565")
QDEF(MP_QSTR_YUV422, (const byte*)"\x0b\x06" "YUV422")
QDEF(MP_QSTR_set_pixel, (const byte*)"\xb0\x09" "set_pixel")
QDEF(MP_QSTR_get_pixel, (const byte*)"\xa4\x09" "get_pixel")
QDEF(MP_QSTR_rgbtuple, (const byte*)"\x6a\x08" "rgbtuple")
QDEF(MP_QSTR_to_rgb565, (const byte*)"\x80\x09" "to_rgb565")
QDEF(MP_QSTR_to_gray, (const byte*)"\x4c\x07" "to_gray")
#endif
